### ISSUE TITLE
RCRColorizedIconImageView storyboard error

### ISSUE THREAD

**Issue by magnett** [robinsonrc/RCRColorizedIconImage#1]
Thanks for this great control!
When you set the class of UIImageView to RCRColorizedIconImageView the storyboard seems to have a compiler error although you can still run the code. 

![screen shot 2015-05-12 at 10 37 34](https://cloud.githubusercontent.com/assets/1730803/7582159/a0774490-f893-11e4-9d11-9eb7265c22a5.png)
![screen shot 2015-05-12 at 10 38 08](https://cloud.githubusercontent.com/assets/1730803/7582161/a36d7250-f893-11e4-83ca-3f8b8954c105.png)

**Comment by robinsonrc** [comment]
Hi, thanks for letting me know!

I'm away from my development Mac at the moment, but I suspect this may be an issue with using the control via CocoaPods. 

Assuming you're using CocoaPods, can you take a look at the following:

http://stackoverflow.com/questions/26567650/live-rendering-a-custom-component-using-ib-designable-from-a-pod-dependency/28108248#28108248

- I think, as long as you're using a recent (or possibly the latest) version of CocoaPods, you can add the following to your Podfile, which will hopefully get things working:

use_frameworks!

Best of luck!
Rich
